const APP_CONFIG = {
  NAME: '快识二维码',
  VERSION: '2.0.0',
  DESCRIPTION: '一键生成网页二维码，框选识别二维码内容'
};

const STORAGE_KEYS = {
  QR_HISTORY: 'qrHistory',
  QR_SETTINGS: 'qrSettings',
  PERFORMANCE_STATS: 'performanceStats'
};

const MESSAGE_TYPES = {
  GET_CURRENT_TAB: 'GET_CURRENT_TAB',
  GET_TAB_INFO: 'GET_TAB_INFO',
  TOGGLE_SELECTION_MODE: 'TOGGLE_SELECTION_MODE',
  START_SELECTION: 'START_SELECTION',
  END_SELECTION: 'END_SELECTION',
  RECOGNIZE_QR: 'RECOGNIZE_QR',
  SAVE_HISTORY: 'SAVE_HISTORY',
  GET_HISTORY: 'GET_HISTORY',
  DELETE_HISTORY: 'DELETE_HISTORY',
  CLEAR_HISTORY: 'CLEAR_HISTORY',
  SAVE_SETTINGS: 'SAVE_SETTINGS',
  GET_SETTINGS: 'GET_SETTINGS',
  LOG_PERFORMANCE: 'LOG_PERFORMANCE',
  GET_PERFORMANCE_STATS: 'GET_PERFORMANCE_STATS'
};

const ERROR_TYPES = {
  NETWORK_ERROR: 'NETWORK_ERROR',
  STORAGE_ERROR: 'STORAGE_ERROR',
  PERMISSION_ERROR: 'PERMISSION_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RUNTIME_ERROR: 'RUNTIME_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
};

const LOG_LEVELS = {
  DEBUG: 0,
  INFO: 1,
  WARN: 2,
  ERROR: 3,
  FATAL: 4
};

const QR_CORRECT_LEVELS = {
  L: 'L',
  M: 'M',
  Q: 'Q',
  H: 'H'
};

const DEFAULT_SETTINGS = {
  size: 200,
  colorDark: '#000000',
  colorLight: '#ffffff',
  correctLevel: QR_CORRECT_LEVELS.H
};

const PERFORMANCE_METRICS = {
  QR_GENERATION_TIME: 'qrGenerationTime',
  QR_RECOGNITION_TIME: 'qrRecognitionTime',
  STORAGE_READ_TIME: 'storageReadTime',
  STORAGE_WRITE_TIME: 'storageWriteTime',
  MESSAGE_RESPONSE_TIME: 'messageResponseTime'
};

const NOTIFICATION_TYPES = {
  SUCCESS: 'success',
  ERROR: 'error',
  INFO: 'info',
  WARNING: 'warning'
};

const NOTIFICATION_DURATION = {
  SHORT: 2000,
  MEDIUM: 3000,
  LONG: 5000
};

const HISTORY_LIMIT = 100;

const SELECTION_MODE = {
  ACTIVE: 'active',
  INACTIVE: 'inactive'
};

const BROWSER_COMPATIBILITY = {
  MIN_CHROME_VERSION: 88,
  MIN_EDGE_VERSION: 88
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    APP_CONFIG,
    STORAGE_KEYS,
    MESSAGE_TYPES,
    ERROR_TYPES,
    LOG_LEVELS,
    QR_CORRECT_LEVELS,
    DEFAULT_SETTINGS,
    PERFORMANCE_METRICS,
    NOTIFICATION_TYPES,
    NOTIFICATION_DURATION,
    HISTORY_LIMIT,
    SELECTION_MODE,
    BROWSER_COMPATIBILITY
  };
}
